In [11]:
#Write a program in python to read and write in a file 

#open the file 
f=open("kavyansh.txt") 
#read the file 
text=f.read() 
#print the text 
print(text)

Installing Python is generally easy, and nowadays many Linux and UNIX distributions include a recent Python. Even some Windows computers (notably those from HP) now come with Python already installed. If you do need to install Python and aren't confident about the task you can find a few notes on the BeginnersGuide/Download wiki page, but installation is unremarkable on most platforms.




In [13]:
# write in a file
# open the file in write mode if no file exits will make new file 
f=open("kavyansh.txt","w") 
# Write some text in a file 
f.write("hi this is kavyansh") 
#close the file 
f.close() 

In [1]:
#write  a program in python to add two numbers 

#input one 
num1=4
#input second 
num2=20

#adding two nos
summ = num1 + num2

print("sum of {0} and {1} is {2}" .format(num1,num2, sum))



sum of 4 and 20 is <built-in function sum>


In [25]:
#Write a python program to check whether the number is positive or negative

def check(n):
     
    # if the number is positive
    if n > 0:
        print("Positive")
         
    # if the number is negative
    elif n < 0:
        print("Negative")

check(5)
check(-5)

Positive
Negative


In [31]:
#Write a python program to find greatest among 3 numbers? 

# taking first number
num1 = int(input("Enter first number: "))           
# taking second number
num2 = int(input("Enter second number: "))          
# taking third number
num3 = int(input("And Enter third number: "))  
 
if (num1 > num2) and (num1 > num3):
   max = num1
elif (num2 > num1) and (num2 > num3):
   max = num2
else:
   max = num3
# printing the max
print("The largest among these three numbers is",max)

Enter first number: 2
Enter second number: 6
And Enter third number: 13
The largest among these three numbers is 13


In [32]:
#Write a python program to print the name of weeks corresponding to number? 

weekday = int(input("Enter weekday day number (1-7) : "))

if weekday == 1 :
    print("\nMonday");

elif weekday == 2 :
    print("\nTuesday")

elif(weekday == 3) :
    print("\nWednesday")

elif(weekday == 4) :
    print("\nThursday")

elif(weekday == 5) :
    print("\nFriday")

elif(weekday == 6) :
    print("\nSaturday")

elif (weekday == 7) :
    print("\nSunday")

else :
    print("\nPlease enter weekday number between 1-7.")


Enter weekday day number (1-7) : 5

Friday


In [38]:
#Write a python program to find the factorial of a number. 

# To take input from the user
num = int(input("Enter a number: "))
factorial = 1

# check if the number is negative, positive or zero
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

Enter a number: 5
The factorial of 5 is 120


In [40]:
#Write a python program to compare the two list? 

list1 = [11, 12, 13, 14, 15]  
list2 = [12, 13, 11, 16, 14]  
  
a = set(list1)  
b = set(list2)  
  
if a == b:  
    print("The list1 and list2 are equal")  
else:  
    print("The list1 and list2 are not equal")  

The list1 and list2 are not equal


In [42]:
#Write a python program to explore the lambda function? 

x = lambda a : a + 10
print(x(5))

15


In [46]:
#Write a python program to explore the filter function in python?


# function that filters vowels
def fun(variable):
    letters = ['a', 'e', 'i', 'o', 'u']
    if (variable in letters):
        return True
    else:
        return False
 
 
# sequence
sequence = ['g', 'e', 'e', 'j', 'k', 's', 'p', 'r']
 
# using filter function
filtered = filter(fun, sequence)
 
print('The filtered letters are:')
for s in filtered:
    print(s)

The filtered letters are:
e
e


In [48]:
#Write a python program to explore the map function in python? 

#Define the function 
def double(ele):     
    return 2*ele 
 
#Define the list 
lst=[10,20,30,40,50] 
 
#printing the result 
print("double element list is: ",list(map(double,lst))) 


double element list is:  [20, 40, 60, 80, 100]


In [51]:
#Write a python program to explore reduce function? 

#importing reduce function 
from functools import reduce 
 #define the function 
def add_ele(a,b): 
    return a+b 
 
#define the list 
lst=[1,2,3,4,5] 
 
#printing the result 
print("the sum of list element is:",reduce(add_ele,lst)) 


the sum of list element is: 15


In [58]:
# using the itertools.accumula#Write a python program to explore accumulate function? 

# import the itertool module 
# to work with it
import itertools
  
# import operator to work 
# with operator
import operator
  
# creating a list lst
lst = [1, 2, 3, 4, 5]te() 
result = itertools.accumulate(GFG, 
                              operator.mul)
  
# printing each item from list
for each in result:
    print(each)

1
2
6
24
120


In [64]:
#Write a python program to explore try-except statement? 

# working of try()
def divide(x, y):
    try:
        # Floor Division : Gives only Fractional Part as Answer
        result = x // y
        print("Yeah ! Your answer is :", result)
    except ZeroDivisionError:
        print("Sorry ! You are dividing by zero ")
 
# Look at parameters and note the working of Program
divide(6, 3)

Yeah ! Your answer is : 2


In [68]:
#write a program to print a month  of particular year using calendar module

import calendar
   
yy = 2017
mm = 11
   
# display the calendar
print(calendar.month(yy, mm))

   November 2017
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30



In [1]:
#Use type, shape and dtype in python? 

import numpy as np 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(arr) 
print(arr.dtype) 
print(type(arr)) 
print(arr.shape) 
 
arr1=np.array([["kavyansh","sanu"],["bhargava","hg"]]) 
print(arr1) 
print(arr1.dtype) 
print(type(arr1[0][0])) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32
<class 'numpy.ndarray'>
(3, 3)
[['kavyansh' 'sanu']
 ['bhargava' 'hg']]
<U8
<class 'numpy.str_'>


In [70]:
#Write a python code to add some days to current date  using date function? 

import datetime 
from datetime import timedelta 
print (datetime.datetime.now()+timedelta(days=2)) 


2023-04-13 23:54:12.436259


In [ ]:
#Use math function in python? 